---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: invidious-https-redirect
  namespace: invidious
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: invidious
  namespace: invidious
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare-production
    traefik.ingress.kubernetes.io/router.entrypoints: web
    # MUST be <namespace>-<name>@kubernetescrd
    traefik.ingress.kubernetes.io/router.middlewares: invidious-invidious-https-redirect@kubernetescrd
spec:
  tls:
    - hosts:
        - invidious.tryrocket.cloud
      secretName: tryrocket-cloud-http-tls
  rules:
    - host: invidious.tryrocket.cloud
      https:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: invidious
                port:
                  number: 3000
