apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
spec:
  type: NodePort
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
  selector:
    app: unbound
