apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
spec:
  type: ClusterIP
  selector:
    app: unbound
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
