apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
data:
  AdGuardHome.yaml: |
    # Paste your AdGuard Home configuration here
    verbosity: normal
    dns:
      bind_host: 0.0.0.0
      port: 53
      upstream_dns:
        - 1.1.1.1
        - 8.8.8.8
