apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: adguard-home
spec:
  externalTrafficPolicy: Local # Keep traffic local to the node
  selector:
    app: adguard-home
  ports:
    - name: dns
      protocol: UDP
      port: 10053
      targetPort: 53
    # - name: dhcp
    #   protocol: UDP
    #   port: 67
    #   targetPort: 67
    - name: http
      protocol: TCP
      port: 10000
      targetPort: 80
    - name: http1
      protocol: TCP
      port: 10001
      targetPort: 3000
  type: LoadBalancer
