apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
        - name: memos
          image: neosmemo/memos:latest
          env:
            - name: MEMOS_PORT
              value: '5230'
          volumeMounts:
            - name: memos-data
              mountPath: /var/opt/memos
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      volumes:
        - name: memos-data
          emptyDir: {} # EmptyDir for temporary data storage (non-persistent)
