apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos
  namespace: memos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
        - name: memos
          image: neosmemo/memos:latest
          args:
            - '--driver'
            - 'postgres'
            - '--dsn'
            - 'postgresql://myuser:mypassword@postgres.postgres.svc.cluster.local:5432/mydatabase1?sslmode=disable'
          env:
            - name: MEMOS_PORT
              value: '5230'
            - name: MEMOS_DRIVER
              value: postgres
            - name: MEMOS_DSN
              value: postgresql://myuser:mypassword@postgres.postgres.svc.cluster.local:5432/mydatabase1?sslmode=disable
          volumeMounts:
            - name: memos-data
              mountPath: /var/opt/memos
          ports:
            - name: http
              containerPort: 5230
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
      volumes:
        - name: memos-data
          emptyDir: {} # EmptyDir for temporary data storage (non-persistent)
