apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tryrocket-cloud
  namespace: default
spec:
  secretName: tryrocket-cloud-http-tls
  issuerRef:
    name: letsencrypt-cloudflare-production
    kind: ClusterIssuer
  commonName: '*.tryrocket.cloud'
  dnsNames:
    - '*.tryrocket.cloud'
