apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare-staging
spec:
  acme:
    # You can also use the staging environment to test your setup:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: max.wassiljew@proton.me
    privateKeySecretRef:
      name: letsencrypt-cloudflare-staging
    solvers:
      - dns01:
          cloudflare:
            email: max.wassiljew@proton.me
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
